DROP SCHEMA public CASCADE;
DROP TABLE users IF EXISTS;
CREATE TABLE users (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
first_name varchar(50),
nick_name varchar(50) NOT NULL,
last_name varchar(50) NOT NULL,
password varchar(50) NOT NULL
);

DROP TABLE posts IF EXISTS;
CREATE TABLE posts (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
user_id integer NOT NULL,
content varchar(250),
creation_date timestamp,
is_public boolean,
FOREIGN KEY (user_id) REFERENCES users(id)
);

DROP TABLE followers IF EXISTS;
CREATE TABLE followers (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
follower_id integer NOT NULL,
followed_id integer NOT NULL,
FOREIGN KEY (follower_id) REFERENCES users(id),
FOREIGN KEY (followed_id) REFERENCES users(id)
);
